---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    name: payment
    app: payment
    product: benchmark
  namespace: benchmark
spec:
  replicas: 1
  selector:
    matchLabels:
      name: payment
  template:
    metadata:
      labels:
        name: payment
        department: benchmark
    spec:
      containers:
      - name: payment
        image: weaveworksdemos/payment:0.4.3
        resources:
          limits:
            cpu: 30m
            memory: 30Mi
          requests:
            cpu: 15m
            memory: 15Mi
        ports:
        - containerPort: 80
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          capabilities:
            drop:
              - all
            add:
              - NET_BIND_SERVICE
          readOnlyRootFilesystem: true
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 300
          timeoutSeconds: 120
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 120
      nodeSelector:
        kubernetes.io/os: linux
        namespace: benchmark
      tolerations:
        - key: "namespace"
          operator: "Equal"
          value: "benchmark"
          effect: "NoSchedule"

