apiVersion: v1
kind: Service
metadata:
  name: load-test-service
  namespace: load-test
spec:
  type: NodePort
  selector:
    app: load-test-master
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8089
