apiVersion: batch/v1
kind: Job
metadata:
  name: load-test-master
  labels:
    role: load-test-master
    app: load-test-master
  namespace: load-test
spec:
  # replicas: 1
  # selector:
  #   matchLabels:
  #     role: load-test-master
  #     app: load-test-master
  #ttlSecondsAfterFinished: 1
  template:
    metadata:
      labels:
        role: load-test-master
        app: load-test-master
    spec:
      containers:
      - image: locustio/locust
        name: master
        args: ["--master"]
        # securityContext:
        #       allowPrivilegeEscalation: false
        #       runAsUser: 0    
        volumeMounts:
          - mountPath: /home/locust/locustfile.py
            name: locust-scripts
            subPath: locustfile.py
          - mountPath: /home/locust/
            name: locust-conf
            #subPath: locust.conf
          - mountPath: /home/locust/reports
            name: locust-reports
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 10
      volumes:
      - name: locust-scripts
        configMap:
          name: scripts-cm
      - name: locust-conf
        hostPath:
          path: /tmp
      - name: locust-reports
        hostPath:
          path: /tmp
      nodeSelector:
        beta.kubernetes.io/os: linux
        namespace: load-test
      tolerations:
        - key: "namespace"
          operator: "Equal"
          value: "load-test"
          effect: "NoSchedule"        
         
