apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-test-nodes
  labels:
    role: load-test-nodes
    app: load-test-nodes
  namespace: load-test
spec:
  replicas: 3
  selector:
    matchLabels:
      role: load-test-nodes
      app: load-test-nodes
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        role: load-test-nodes
        app: load-test-nodes
    spec:
      containers:
      - image: locustio/locust
        name: worker
        args: ["--worker", "--master-host=load-test-master", "--headless"]
        volumeMounts:
          - mountPath: /home/locust/locustfile.py
            name: locust-scripts
            subPath: locustfile.py
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 10
      volumes:
      - name: locust-scripts
        configMap:
          name: scripts-cm
      nodeSelector:
        beta.kubernetes.io/os: linux
        namespace: load-test
      tolerations:
        - key: "namespace"
          operator: "Equal"
          value: "load-test"
          effect: "NoSchedule"        

