FROM maven:3.8.6-openjdk-8 as build-maven

RUN apt-get update && apt-get install wget -y
WORKDIR /repos
RUN mkdir bin

#Build Carts
ARG NAME=carts
ARG TAG=0.4.8
ENV FILE=${TAG}.zip
ENV COMPLETE_FILE_NAME=${NAME}'-'${FILE}
ARG REPO_ROOT=https://github.com/microservices-demo/ \
    REPO_ARCHIVE_PATH=/archive/refs/tags/
ENV REPO=${REPO_ROOT}${NAME}${REPO_ARCHIVE_PATH}${FILE}
ENV SCRIPT_DIR=${NAME}'-'${TAG}'/'
ENV BIN_DIR='/repos/bin'   

RUN wget ${REPO} -O ${COMPLETE_FILE_NAME}
RUN unzip ${COMPLETE_FILE_NAME}
RUN mvn -f ${SCRIPT_DIR} -DskipTests package
RUN cp ${SCRIPT_DIR}/target/*.jar ${BIN_DIR}

#Build Orders
ARG NAME=orders
ARG TAG=0.4.7
ENV FILE=${TAG}.zip
ENV COMPLETE_FILE_NAME=${NAME}'-'${FILE}
ARG REPO_ROOT=https://github.com/microservices-demo/ \
    REPO_ARCHIVE_PATH=/archive/refs/tags/
ENV REPO=${REPO_ROOT}${NAME}${REPO_ARCHIVE_PATH}${FILE}
ENV SCRIPT_DIR=${NAME}'-'${TAG}'/'
ENV BIN_DIR='/repos/bin'   

RUN wget ${REPO} -O ${COMPLETE_FILE_NAME}
RUN unzip ${COMPLETE_FILE_NAME}
COPY application.properties ${SCRIPT_DIR}/src/main/resources
COPY OrdersConfigurationProperties.java ${SCRIPT_DIR}/src/main/java/works/weave/socks/orders/config
RUN mvn -f ${SCRIPT_DIR} -DskipTests package
RUN cp ${SCRIPT_DIR}/target/*.jar ${BIN_DIR}

#Build shipping
ARG NAME=shipping
ARG TAG=0.4.8
ENV FILE=${TAG}.zip
ENV COMPLETE_FILE_NAME=${NAME}'-'${FILE}
ARG REPO_ROOT=https://github.com/microservices-demo/ \
    REPO_ARCHIVE_PATH=/archive/refs/tags/
ENV REPO=${REPO_ROOT}${NAME}${REPO_ARCHIVE_PATH}${FILE}
ENV SCRIPT_DIR=${NAME}'-'${TAG}'/'
ENV BIN_DIR='/repos/bin'   

RUN wget ${REPO} -O ${COMPLETE_FILE_NAME}
RUN unzip ${COMPLETE_FILE_NAME}
RUN mvn -f ${SCRIPT_DIR} -DskipTests package
RUN cp ${SCRIPT_DIR}/target/*.jar ${BIN_DIR}

#Build queue
ARG NAME=queue-master
ARG TAG=0.3.1
ENV FILE=${TAG}.zip
ENV COMPLETE_FILE_NAME=${NAME}'-'${FILE}
ARG REPO_ROOT=https://github.com/microservices-demo/ \
    REPO_ARCHIVE_PATH=/archive/refs/tags/
ENV REPO=${REPO_ROOT}${NAME}${REPO_ARCHIVE_PATH}${FILE}
ENV SCRIPT_DIR=${NAME}'-'${TAG}'/'
ENV BIN_DIR='/repos/bin'   

RUN wget ${REPO} -O ${COMPLETE_FILE_NAME}
RUN unzip ${COMPLETE_FILE_NAME}
RUN mvn -f ${SCRIPT_DIR} -DskipTests package
RUN cp ${SCRIPT_DIR}/target/*.jar ${BIN_DIR}


FROM openjdk:8
ENV JAVA_OPTS "-Djava.security.egd=file:/dev/urandom"


#Cria o diretório base do container
WORKDIR /usr/src/

#Copia os binários das aplicações para o diretorio base
COPY --from=build-maven /repos/bin /usr/src/bin/
COPY run-apps-jvm.sh /usr/src/scripts/

#Copia a aplicação front-end para o diretorio de aplicações
#COPY ./front-end /usr/src/app/front-end
EXPOSE 8081-8083
CMD ["sh","scripts/run-apps-jvm.sh"]
