---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: by-stack-go
  namespace: by-stack
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: by-stack-go
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 150
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 150
