---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: by-stack-node
  labels:
    name: front-end
    app: front-end
    product: by-stack-node
  namespace: by-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      name: by-stack-node
  template:
    metadata:
      labels:
        name: by-stack-node
        department: by-stack
    spec:
      containers:
      - name: bystacknode
        image: buzatof/by-stack-node
        resources:
          limits:
            cpu: 930m
            memory: 680Mi
          requests:
            cpu: 465m
            memory: 340Mi
        ports:
        - containerPort: 8079
        env:
        - name: SESSION_REDIS
          value: "true"        
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          capabilities:
            drop:
              - all
          readOnlyRootFilesystem: true
        startupProbe:
          httpGet:
            path: /
            port: 8079
          failureThreshold: 30
          periodSeconds: 10          
        readinessProbe:
          httpGet:
             path: /
             port: 8079
          periodSeconds: 30
          timeoutSeconds: 120
          failureThreshold: 10
          initialDelaySeconds: 30

        # readinessProbe:
        #   httpGet:
        #      path: /metrics
        #      port: 8079
        #   periodSeconds: 30
        #   timeoutSeconds: 120
        #   failureThreshold: 10
        #   initialDelaySeconds: 30
        # livenessProbe:
        #   httpGet:
        #     path: /metrics
        #     port: 8079
        #   initialDelaySeconds: 300
        #   timeoutSeconds: 120
        #   periodSeconds: 30
        #   failureThreshold: 10
        # readinessProbe:
        #   httpGet:
        #     path: /metrics
        #     port: 8079
        #   initialDelaySeconds: 180
          # timeoutSeconds: 3
      nodeSelector:
        kubernetes.io/os: linux
        namespace: by-stack
      tolerations:
        - key: "namespace"
          operator: "Equal"
          value: "by-stack"
          effect: "NoSchedule"
