---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: by-stack-go
  labels:
    name: by-stack-go
  namespace: by-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      name: by-stack-go
  template:
    metadata:
      labels:
        name: by-stack-go
        department: by-stack
    spec:
      containers:
      - name: bystackgo
        image: buzatof/by-stack-go
        env:
          - name: ZIPKIN
            value: zipkin.jaeger.svc.cluster.local
          - name: MONGO_HOST
            value: user-db:27017
          - name: mongo
            value: user-db:27017            
        resources:
          limits:
            cpu: 700m
            memory: 600Mi
          requests:
            cpu: 299m
            memory: 300Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 8084
          initialDelaySeconds: 300
          timeoutSeconds: 120
        readinessProbe:
          httpGet:
            path: /health
            port: 8084
          httpGet:
            path: /health
            port: 8085
          httpGet:
            path: /health
            port: 8086
          initialDelaySeconds: 180
          timeoutSeconds: 120
        ports:
        - containerPort: 80
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          capabilities:
            drop:
              - all
            add:
              - NET_BIND_SERVICE
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
      nodeSelector:
        kubernetes.io/os: linux
        namespace: by-stack
      tolerations:
        - key: "namespace"
          operator: "Equal"
          value: "by-stack"
          effect: "NoSchedule"
