---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: all-in-one
  labels:
    name: all-in-one    
    app: all-in-one
    product: all-in-one
  namespace: all-in-one
spec:
  replicas: 1
  selector:
    matchLabels:
      name: all-in-one
  template:
    metadata:
      labels:
        name: all-in-one    
        department: all-in-one
        app: all-in-one
        product: all-in-one
    spec:
      containers:
      - name: allinone
        image: buzatof/all-in-one
        env:
          - name: ZIPKIN
            value: zipkin.jaeger.svc.cluster.local
          - name: MONGO_HOST
            value: user-db:27017
          - name: mongo
            value: user-db:27017
          - name: SESSION_REDIS
            value: "true"
        resources:
          limits:
            cpu: 3640m
            memory: 2740Mi
          requests:
            cpu: 1820m
            memory: 1370Mi
        # livenessProbe:
        #   httpGet:
        #      path: /
        #      port: 8079
        #   initialDelaySeconds: 300            
        #   periodSeconds: 10
        #   failureThreshold: 30
        startupProbe:
          httpGet:
            path: /
            port: 8079
          failureThreshold: 30
          periodSeconds: 10          
        readinessProbe:
          httpGet:
             path: /
             port: 8079
          periodSeconds: 30
          timeoutSeconds: 120
          failureThreshold: 10
          initialDelaySeconds: 30
        ports:
        - containerPort: 8079
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          capabilities:
            drop:
              - all
            add:
              - NET_BIND_SERVICE
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
      nodeSelector:
        kubernetes.io/os: linux
        namespace: all-in-one
      tolerations:
        - key: "namespace"
          operator: "Equal"
          value: "all-in-one"
          effect: "NoSchedule"
