---
apiVersion: v1
kind: Service
metadata:
  name: all-in-one
  annotations:
        prometheus.io/scrape: 'true'
  labels:
    name: all-in-one    
    app: all-in-one
    product: all-in-one
  namespace: all-in-one
spec:
  ports:
    # the port that this service should serve on
  - name: front-end
    port: 80
    targetPort: 8079
  - name: carts
    port: 8081
    targetPort: 8081
  - name: orders
    port: 8082
    targetPort: 8082
  - name: shipping
    port: 8083
    targetPort: 8083
  - name: catalogue
    port: 8084
    targetPort: 8084
  - name: payment
    port: 8085
    targetPort: 8085
  - name: user
    port: 8086
    targetPort: 8086
  - name: queue-master
    port: 8087
    targetPort: 8087
  selector:
    name: all-in-one