---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: all-in-one
  namespace: all-in-one
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: all-in-one
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 150
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 150
