version: '2'

services:
  front-end:
    image: weaveworksdemos/front-end:0.3.12
    hostname: front-end
    restart: always
    cap_drop:
      - all
    read_only: true
    labels:
      # Enable public access
      - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=8079"
  proxy:
    image: traefik:v2.4.2
    command:
      # - "--log.level=DEBUG"
      - "--api=true"
      - "--api.dashboard=true"
      - "--api.insecure=true" # Don't do that in production
      - "--providers.docker"
      - "--entrypoints.web.address=:80"
    volumes:
          - type: bind
            source: /var/run/docker.sock
            target: /var/run/docker.sock
            read_only: true
    ports:
          - target: 80
            published: 80
            protocol: tcp
            mode: host
          - target: 8080
            published: 8080
            protocol: tcp
            mode: host
  # edge-router:
  #   image: weaveworksdemos/edge-router:0.1.1
  #   ports:
  #     - '80:80'
  #     - '8080:8080'
  #   cap_drop:
  #     - all
  #   cap_add:
  #     - NET_BIND_SERVICE
  #     - CHOWN
  #     - SETGID
  #     - SETUID
  #     - DAC_OVERRIDE
  #   read_only: true
  #   tmpfs:
  #     - /var/run:rw,noexec,nosuid
  #   hostname: edge-router
  #   restart: always
  all-in-one:
    image: teste
    ports:      
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
      - "8084:8084"
      - "8085:8085"
      - "8086:8086"
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    labels:
      - "traefik.http.routers.catalogue.rule=PathPrefix(`/catalogue/`)"
      - "traefik.http.services.catalogue.loadbalancer.server.port=8084"
      - "traefik.http.routers.cart.rule=PathPrefix(`/cart/`)"
      - "traefik.http.services.cart.loadbalancer.server.port=8081"
    environment:
      - MONGO_HOST=user-db:27017
      - JAVA_OPTS=-Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false          
    tmpfs:
      - /tmp:rw,noexec,nosuid
  catalogue-db:
    image: weaveworksdemos/catalogue-db:0.3.0
    hostname: catalogue-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=socksdb
  carts-db:
    image: mongo:3.4
    hostname: carts-db
    restart: always
    cap_drop:
      - all
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid
  orders-db:
    image: mongo:3.4
    hostname: orders-db
    restart: always
    cap_drop:
      - all
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid
  rabbitmq:
    image: rabbitmq:3.6.8
    hostname: rabbitmq
    restart: always
    cap_drop:
      - all
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    read_only: true
  user-db:
    image: weaveworksdemos/user-db:0.4.0
    hostname: user-db
    restart: always
    cap_drop:
      - all
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid