---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: by-stack-jvm
  labels:
    name: by-stack-jvm
  namespace: sock-shop-by-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      name: by-stack-jvm
  template:
    metadata:
      labels:
        name: by-stack-jvm
    spec:
      containers:
      - name: bystackjvm
        image: buzatof/by-stack-jvm
        env:
          - name: ZIPKIN
            value: zipkin.jaeger.svc.cluster.local
          - name: JAVA_OPTS
            value: -Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false
        resources:
          limits:
            cpu: 500m
            memory: 1000Mi
          requests:
            cpu: 100m
            memory: 300Mi
        ports:
        - containerPort: 80
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          capabilities:
            drop:
              - all
            add:
              - NET_BIND_SERVICE
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
      nodeSelector:
        beta.kubernetes.io/os: linux
        namespace: sock-shop-by-stack
