{
 "title": "Performance Experiment",
 "time": { "from": "now-10m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Catalogue QPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(request_duration_seconds_count{status_code=~\"2..\",route!~\"metrics|health\",instance=~\".*80|.*8084\", name=~\"catalogue|all-in-one|by-stack-go\"}[1m])) by (kubernetes_namespace)",
     "legendFormat": "2xx - {{kubernetes_namespace}}"
    },
    {
     "expr": "sum(rate(request_duration_seconds_count{name=\"catalogue\",status_code=~\"4.+|5.+\",instance=~\".*80|.*8084\", name=~\"catalogue|all-in-one|by-stack-go|by-dependencies\"}[1m])) by (kubernetes_namespace)",
     "legendFormat": "4xx/5xx - {{kubernetes_namespace}}"
    }
   ]
  },
  {
   "title": "Catalogue latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(request_duration_seconds_bucket{route!~\"metrics|health\",instance=~\".*80|.*8084\", name=~\"catalogue|all-in-one|by-stack-go\"}[1m])) by (kubernetes_namespace, le))",
     "legendFormat": "99th quantile - {{kubernetes_namespace}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(request_duration_seconds_bucket{route!~\"metrics|health\",instance=~\".*80|.*8084\", name=~\"catalogue|all-in-one|by-stack-go\"}[1m])) by (kubernetes_namespace, le))",
     "legendFormat": "50th quantile - {{kubernetes_namespace}}"
    },
    {
     "expr": "sum(rate(request_duration_seconds_sum{route!~\"metrics|health\",instance=~\".*80|.*8084\", name=~\"catalogue|all-in-one|by-stack-go\"}[1m])) by (kubernetes_namespace) / sum(rate(request_duration_seconds_count{route!~\"metrics|health\",instance=~\".*80|.*8084\", name=~\"catalogue|all-in-one|by-stack-go\"}[1m])) by (kubernetes_namespace)",
     "legendFormat": "Mean - {{kubernetes_namespace}}"
    }
   ]
  },
  {
   "title": "Cart QPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(request_duration_seconds_count{status_code=~\"2..\",route!~\"metrics|health\", instance=~\".*80|.*8081\",name=~\"carts|all-in-one|by-stack-jvm\"}[1m])) by (kubernetes_namespace)",
     "legendFormat": "2xx - {{kubernetes_namespace}}"
    },
    {
     "expr": "sum(rate(request_duration_seconds_count{name=\"carts\",status_code=~\"4.+|5.+\",instance=~\".*80|.*8081\",name=~\"carts|all-in-one|by-stack-jvm\"}[1m]))by (kubernetes_namespace)",
     "legendFormat": "4xx/5xx - {{kubernetes_namespace}}"
    }
   ]
  },
  {
   "title": "Cart latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(request_duration_seconds_bucket{instance=~\".*80|.*8081\",name=~\"carts|all-in-one|by-stack-jvm\"}[1m])) by (kubernetes_namespace, le))",
     "legendFormat": "99th quantile - {{kubernetes_namespace}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(request_duration_seconds_bucket{instance=~\".*80|.*8081\",name=~\"carts|all-in-one|by-stack-jvm\"}[1m])) by (kubernetes_namespace, le))",
     "legendFormat": "50th quantile - {{kubernetes_namespace}}"
    },
    {
     "expr": "sum(rate(request_duration_seconds_sum{route!~\"metrics|health\",instance=~\".*80|.*8081\",name=~\"carts|all-in-one|by-stack-jvm\"}[1m]))by (kubernetes_namespace)  / sum(rate(request_duration_seconds_count{route!~\"metrics|health\",instance=~\".*80|.*8081\",name=~\"carts|all-in-one|by-stack-jvm\"}[1m]))by (kubernetes_namespace)  ",
     "legendFormat": "Mean - {{kubernetes_namespace}} "
    }
   ]
  },
  {
   "title": "Orders QPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(request_duration_seconds_count{instance=~\".*80|.*8082\", name=~\"orders|all-in-one|by-stack-jvm|by-dependencies\",status_code=~\"2..\",route!~\"metrics|health\"}[1m]))by (kubernetes_namespace)",
     "legendFormat": "2xx - {{kubernetes_namespace}}"
    },
    {
     "expr": "sum(rate(request_duration_seconds_count{instance=~\".*80|.*8082\", name=~\"orders|all-in-one|by-stack-jvm|by-dependencies\",status_code=~\"4.+|5.+\"}[1m]))by (kubernetes_namespace)",
     "legendFormat": "4xx/5xx - {{kubernetes_namespace}}"
    }
   ]
  },
  {
   "title": "Orders latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(request_duration_seconds_bucket{instance=~\".*80|.*8082\", name=~\"orders|all-in-one|by-stack-jvm|by-dependencies\"}[1m])) by (kubernetes_namespace, le))",
     "legendFormat": "99th quantile - {{kubernetes_namespace}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(request_duration_seconds_bucket{instance=~\".*80|.*8082\", name=~\"orders|all-in-one|by-stack-jvm|by-dependencies\"}[1m])) by (kubernetes_namespace, le))",
     "legendFormat": "50th quantile - {{kubernetes_namespace}}"
    },
    {
     "expr": "sum(rate(request_duration_seconds_sum{route!~\"metrics|health\",instance=~\".*80|.*8082\", name=~\"orders|all-in-one|by-stack-jvm|by-dependencies\"}[1m])) by (kubernetes_namespace) / sum(rate(request_duration_seconds_count{route!~\"metrics|health\",instance=~\".*80|.*8082\", name=~\"orders|all-in-one|by-stack-jvm|by-dependencies\"}[1m])) by (kubernetes_namespace)",
     "legendFormat": "Mean - {{kubernetes_namespace}}"
    }
   ]
  },
  {
   "title": "Payment QPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(request_duration_seconds_count{instance=~\".*80|.*8085\",name=~\"payment|all-in-one|by-stack-go|by-dependencies\",status_code=~\"2..\",route!~\"metrics|health\"}[1m]))by (kubernetes_namespace)",
     "legendFormat": "2xx - {{kubernetes_namespace}}"
    },
    {
     "expr": "sum(rate(request_duration_seconds_count{instance=~\".*80|.*8085\",name=~\"payment|all-in-one|by-stack-go|by-dependencies\",status_code=~\"4.+|5.+\"}[1m]))by (kubernetes_namespace)",
     "legendFormat": "4xx/5xx - {{kubernetes_namespace}}"
    }
   ]
  },
  {
   "title": "Payment latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(request_duration_seconds_bucket{instance=~\".*80|.*8085\",name=~\"payment|all-in-one|by-stack-go|by-dependencies\",route!~\"health|metrics\"}[1m])) by (kubernetes_namespace, le))",
     "legendFormat": "99th quantile - {{kubernetes_namespace}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(request_duration_seconds_bucket{instance=~\".*80|.*8085\",name=~\"payment|all-in-one|by-stack-go|by-dependencies\",route!~\"health|metrics\"}[1m])) by (kubernetes_namespace, le))",
     "legendFormat": "50th quantile - {{kubernetes_namespace}}"
    },
    {
     "expr": "sum(rate(request_duration_seconds_sum{route!~\"metrics|health\",instance=~\".*80|.*8085\",name=~\"payment|all-in-one|by-stack-go|by-dependencies\"}[1m])) by (kubernetes_namespace) / sum(rate(request_duration_seconds_count{route!~\"metrics|health\",instance=~\".*80|.*8085\",name=~\"payment|all-in-one|by-stack-go|by-dependencies\"}[1m])) by (kubernetes_namespace)",
     "legendFormat": "Mean - {{kubernetes_namespace}}"
    }
   ]
  },
  {
   "title": "Shipping QPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(request_duration_seconds_count{instance=~\".*80|.*8083\",name=~\"shipping|all-in-one|by-stack-jvm|by-dependencies\" ,status_code=~\"2..\",route!~\"metrics|health\"}[1m]))by (kubernetes_namespace) ",
     "legendFormat": "2xx - {{kubernetes_namespace}}"
    },
    {
     "expr": "sum(rate(request_duration_seconds_count{instance=~\".*80|.*8083\",name=~\"shipping|all-in-one|by-stack-jvm|by-dependencies\",status_code=~\"4.+|5.+\"}[1m]))by (kubernetes_namespace)  * 100",
     "legendFormat": "4xx/5xx - {{kubernetes_namespace}}"
    }
   ]
  },
  {
   "title": "Shipping latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(request_duration_seconds_bucket{route!~\"metrics|health\",instance=~\".*80|.*8083\",name=~\"shipping|all-in-one|by-stack-jvm|by-dependencies\"}[1m])) by (kubernetes_namespace, le))",
     "legendFormat": "99th quantile - {{kubernetes_namespace}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(request_duration_seconds_bucket{route!~\"metrics|health\",instance=~\".*80|.*8083\",name=~\"shipping|all-in-one|by-stack-jvm|by-dependencies\"}[1m])) by (kubernetes_namespace, le))",
     "legendFormat": "50th quantile - {{kubernetes_namespace}}"
    },
    {
     "expr": "sum(rate(request_duration_seconds_sum{route!~\"metrics|health\",instance=~\".*80|.*8083\",name=~\"shipping|all-in-one|by-stack-jvm|by-dependencies\"}[1m])) by (kubernetes_namespace) / sum(rate(request_duration_seconds_count{instance=~\".*80|.*8083\",name=~\"shipping|all-in-one|by-stack-jvm|by-dependencies\"}[1m])) by (kubernetes_namespace)",
     "legendFormat": "Mean - {{kubernetes_namespace}}"
    }
   ]
  },
  {
   "title": "User QPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(request_duration_seconds_count{instance=~\".*80|.*8086\", name=~\"user|all-in-one|by-stack-go\",status_code=~\"2..\",route!~\"metrics|health\"}[1m]))by (kubernetes_namespace)",
     "legendFormat": "2xx - {{kubernetes_namespace}}"
    },
    {
     "expr": "sum(rate(request_duration_seconds_count{instance=~\".*80|.*8086\", name=~\"user|all-in-one|by-stack-go\",status_code=~\"4.+|5.+\"}[1m])) by (kubernetes_namespace)",
     "legendFormat": "4xx/5xx - {{kubernetes_namespace}}"
    }
   ]
  },
  {
   "title": "User latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(request_duration_seconds_bucket{instance=~\".*80|.*8086\", name=~\"user|all-in-one|by-stack-go\", route!~\"metrics|health\"}[1m])) by (kubernetes_namespace, le))",
     "legendFormat": "99th quantile - {{kubernetes_namespace}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(request_duration_seconds_bucket{instance=~\".*80|.*8086\", name=~\"user|all-in-one|by-stack-go\", route!~\"metrics|health\"}[1m])) by (kubernetes_namespace, le))",
     "legendFormat": "50th quantile - {{kubernetes_namespace}}"
    },
    {
     "expr": "sum(rate(request_duration_seconds_sum{instance=~\".*80|.*8086\", name=~\"user|all-in-one|by-stack-go\", route!~\"metrics|health\"}[1m])) by (kubernetes_namespace) / sum(rate(request_duration_seconds_count{instance=~\".*80|.*8086\", name=~\"user|all-in-one|by-stack-go\", route!~\"metrics|health\"}[1m])) by (kubernetes_namespace)",
     "legendFormat": "Mean - {{kubernetes_namespace}}"
    }
   ]
  },
  {
   "title": "Frontend QPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(request_duration_seconds_count{instance=~\".*8079\",status_code=~\"2..\",route!~\"metrics|health\"}[1m]))by (kubernetes_namespace)",
     "legendFormat": "2xx - {{kubernetes_namespace}}"
    },
    {
     "expr": "sum(rate(request_duration_seconds_count{instance=~\".*8079\",status_code=~\"4.+|5.+\"}[1m])) by (kubernetes_namespace)",
     "legendFormat": "4xx/5xx - {{kubernetes_namespace}}"
    }
   ]
  },
  {
   "title": "Frontend latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(request_duration_seconds_bucket{instance=~\".*8079\"}[1m])) by (kubernetes_namespace, le))",
     "legendFormat": "99th quantile - {{kubernetes_namespace}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(request_duration_seconds_bucket{instance=~\".*8079\"}[1m])) by (kubernetes_namespace, le))",
     "legendFormat": "50th quantile - {{kubernetes_namespace}}"
    },
    {
     "expr": "sum(rate(request_duration_seconds_sum{instance=~\".*8079\"}[1m])) by (kubernetes_namespace) / sum(rate(request_duration_seconds_count{instance=~\".*8079\"}[1m])) by (kubernetes_namespace)",
     "legendFormat": "Mean - {{kubernetes_namespace}}"
    }
   ]
  }
 ]
}