---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-db
  labels:
    name: orders-db
    app: orders-db
    product: benchmark
  namespace: benchmark
spec:
  replicas: 1
  selector:
    matchLabels:
      name: orders-db
  template:
    metadata:
      labels:
        name: orders-db
        department: benchmark
    spec:
      containers:
      - name: orders-db
        image: mongo:5.0.11
        ports:
        - name: mongo
          containerPort: 27017
        securityContext:
          capabilities:
            drop:
              - all
            add:
              - CHOWN
              - SETGID
              - SETUID
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
      nodeSelector:
        kubernetes.io/os: linux
        namespace: benchmark
      tolerations:
        - key: "namespace"
          operator: "Equal"
          value: "benchmark"
          effect: "NoSchedule"

