spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 9090
    nodePort: 30518
  selector:
    app: prometheus

# kubectl patch svc kubecost-prometheus-server --patch "$(cat prometheus-svc.yaml)" -n kubecost
