# kubectl create namespace kubecost
# helm repo add kubecost https://kubecost.github.io/cost-analyzer/
# helm install kubecost kubecost/cost-analyzer --namespace kubecost --set kubecostToken="ZmJ1emF0b0BpbWUudXNwLmJyxm343yadf98" --values values.yaml
# helm install kubecost/cost-analyzer --name kubecost --values values.yaml
# helm install kubecost cost-analyzer --repo https://kubecost.github.io/cost-analyzer/ --namespace kubecost --create-namespace --values values.yaml


# helm upgrade -i kubecost oci://public.ecr.aws/kubecost/cost-analyzer --version 1.104.0 --namespace kubecost --create-namespace -f https://raw.githubusercontent.com/kubecost/cost-analyzer-helm-chart/develop/cost-analyzer/values-eks-cost-monitoring.yaml --set prometheus.server.retention=30d --set prometheus.server.persistentVolume.size=64Gi

prometheus:
  server:
    retention: 30d
    persistentVolume:
      size: 64Gi

networkCosts:
  enabled: true
  # nodeSelector:
  #   kubernetes.io/os: linux
  #   namespace: kubecost
grafana:
  sidecar:
    dashboards:
      enabled: false
# prometheus:
#   server:
#     persistentVolume:
#       storageClass: gp2
# persistentVolume:
#   storageClass: gp2


# nodeSelector:
#   kubernetes.io/os: linux
#   namespace: kubecost
# kubecostMetrics:
#     nodeSelector:
#       kubernetes.io/os: linux
#       namespace: kubecost
