# kubectl create namespace kubecost
# helm repo add kubecost https://kubecost.github.io/cost-analyzer/
# helm install kubecost kubecost/cost-analyzer --namespace kubecost --set kubecostToken="ZmJ1emF0b0BpbWUudXNwLmJyxm343yadf98" --values values.yaml
# helm install kubecost/cost-analyzer --name kubecost --values values.yaml
#  helm install kubecost cost-analyzer --repo https://kubecost.github.io/cost-analyzer/ --namespace kubecost --create-namespace --values values.yaml

networkCosts:
  enabled: true
  # nodeSelector:
  #   kubernetes.io/os: linux
  #   namespace: kubecost
grafana:
  sidecar:
    dashboards:
      enabled: true
# prometheus:
#   server:
#     persistentVolume:
#       storageClass: gp2
# persistentVolume:
#   storageClass: gp2


# nodeSelector:
#   kubernetes.io/os: linux
#   namespace: kubecost
# kubecostMetrics:
#     nodeSelector:
#       kubernetes.io/os: linux
#       namespace: kubecost
