---
apiVersion: v1
kind: Service
metadata:
  name: by-dependencies
  annotations:
        prometheus.io/scrape: 'true'
  labels:
    name: by-dependencies
  namespace: by-dependencies
spec:
  #type: NodePort
  ports:
    # the port that this service should serve on
  - name: orders
    port: 8082
    targetPort: 8082
    #nodePort: 30303
  - name: shipping
    port: 8083
    targetPort: 8083
    #nodePort: 30304
  - name: payment
    port: 8085
    targetPort: 8085
    #nodePort: 30306
  selector:
    name: by-dependencies
