---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue-master
  labels:
    name: queue-master
  namespace: by-dependencies
spec:
  replicas: 1
  selector:
    matchLabels:
      name: queue-master
  template:
    metadata:
      labels:
        name: queue-master
        department: by-dependencies
    spec:
      containers:
      - name: queue-master
        image: weaveworksdemos/queue-master:0.3.1
        env:
         - name: JAVA_OPTS
           value: -Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false
        resources:
          limits:
            cpu: 300m
            memory: 400Mi
          requests:
            cpu: 150m
            memory: 200Mi
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 120
          timeoutSeconds: 120
        ports:
        - containerPort: 80
      nodeSelector:
        kubernetes.io/os: linux
        namespace: by-dependencies
      tolerations:
        - key: "namespace"
          operator: "Equal"
          value: "by-dependencies"
          effect: "NoSchedule"
