---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: all-in-one
  labels:
    name: all-in-one
  namespace: sock-shop-all-in-one
spec:
  replicas: 1
  selector:
    matchLabels:
      name: all-in-one
  template:
    metadata:
      labels:
        name: all-in-one
    spec:
      containers:
      - name: allinone
        image: buzatof/all-in-one
        env:
          - name: ZIPKIN
            value: zipkin.jaeger.svc.cluster.local
          - name: JAVA_OPTS
            value: -Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false
          - name: MONGO_HOST
            value: user-db:27017
          - name: mongo
            value: user-db:27017
          - name: SESSION_REDIS
            value: "true"
        resources:
          limits:
            cpu: 3000m
            memory: 2100Mi
          requests:
            cpu: 100m
            memory: 300Mi
        ports:
        - containerPort: 80
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          capabilities:
            drop:
              - all
            add:
              - NET_BIND_SERVICE
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
      nodeSelector:
        beta.kubernetes.io/os: linux
        namespace: sock-shop-all-in-one
