---
apiVersion: v1
kind: Service
metadata:
  name: all-in-one
  annotations:
        prometheus.io/scrape: 'true'
  labels:
    name: all-in-one
  namespace: sock-shop-all-in-one
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
  - name: front-end
    port: 80
    targetPort: 8079
    nodePort: 30101
  - name: carts
    port: 8081
    targetPort: 8081
    nodePort: 30102
  - name: orders
    port: 8082
    targetPort: 8082
    nodePort: 30103
  - name: shipping
    port: 8083
    targetPort: 8083
    nodePort: 30104
  - name: catalogue
    port: 8084
    targetPort: 8084
    nodePort: 30105
  - name: payment
    port: 8085
    targetPort: 8085
    nodePort: 30106
  - name: user
    port: 8086
    targetPort: 8086
    nodePort: 30107
  - name: queue-master
    port: 8087
    targetPort: 8087
    nodePort: 30108
  selector:
    name: all-in-one